max_epochs: 100
accelerator: auto
devices: auto
strategy: ddp_find_unused_parameters_true
precision: bf16-mixed
sync_batchnorm: True
limit_train_batches: 1.0
limit_val_batches: 1.0
detect_anomaly: false
enable_checkpointing: true
